name: Docker CI/CD

on:
  push:
    branches: [main]
    paths-ignore:
      - 'packages/sdk/**'
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'packages/sdk/**'
      - 'docs/**'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/litebase:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/litebase:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/litebase:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/litebase:buildcache,mode=max
